"""Migration generator. The only sanctioned way to add a file under migrations/.

    python3 tools/make_migration.py add_symbol_index

Writes the next numbered revision with an empty UP/DOWN for the author to fill. Existing
revisions are never rewritten: once a file here has been applied it is history.
"""
import sys
from pathlib import Path

MIGRATIONS = Path(__file__).resolve().parent.parent / "migrations"

TEMPLATE = '''"""Generated by tools/make_migration.py. Applied: not yet."""

REVISION = "{revision}"
DOWN_REVISION = {down}

UP: list[str] = []

DOWN: list[str] = []
'''


def existing() -> list[Path]:
    return sorted(p for p in MIGRATIONS.glob("[0-9]*.py"))


def main(name: str) -> int:
    prior = existing()
    # Number from the highest revision on disk, not the count: a deleted file would
    # otherwise hand out a number that is already history.
    highest = int(prior[-1].name[:4]) if prior else 0
    revision = f"{highest + 1:04d}_{name}"
    out = MIGRATIONS / f"{revision}.py"
    out.write_text(
        TEMPLATE.format(revision=revision, down=repr(prior[-1].stem) if prior else None),
        encoding="utf-8",
    )
    print(f"wrote migrations/{out.name}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: make_migration.py <name>", file=sys.stderr)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1]))
