"""Generated by tools/make_migration.py on 2026-06-01. Applied 2026-06-01.

Do not edit: the file records what already ran against every environment. A change
here makes the recorded history disagree with the deployed schema.
"""

REVISION = "0001_initial"
DOWN_REVISION = None

UP = [
    "CREATE TABLE portfolio (id INTEGER PRIMARY KEY, owner TEXT NOT NULL)",
    "CREATE TABLE holding (id INTEGER PRIMARY KEY, portfolio_id INTEGER NOT NULL,"
    " symbol TEXT NOT NULL, units INTEGER NOT NULL)",
    "CREATE INDEX ix_holding_portfolio_id ON holding (portfolio_id)",
]

DOWN = [
    "DROP INDEX ix_holding_portfolio_id",
    "DROP TABLE holding",
    "DROP TABLE portfolio",
]
